---
title: "HW6"
author: "Xing Chen"
data: 2019-11-23
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(modelr)
library(mgcv)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```


## Problem 1

### Load and clean 

import the dataset

```{r}
child_bw_data = read_csv(file = "./data/birthweight.csv")
```

change numeric variables with categorical values to factor variables

```{r}
child_bw_data = 
child_bw_data %>% 
  mutate(
    babysex = as.factor(babysex),
    babysex = recode(babysex, "1" = "male", "2" = "female"),
    malform = as.factor(malform), 
    malform = recode(malform, "0" = "absent", "1" = "present"), 
    frace = as.factor(frace), 
    frace = recode(frace, "1" = "White", "2"  = "Black", "3" = "Asian", "4" = "Puerto Rican", 
                  "8" = "Other", "9" = "Unkown"), 
    mrace = as.factor(mrace), 
    mrace = recode(frace, "1" = "White", "2"  = "Black", "3" = "Asian", "4" = "Puerto Rican", 
                  "8" = "Other")
 )

child_bw_data %>% 
  select(babysex, malform, frace, mrace) %>% 
  map(~levels(.x))
```

create my own regression model for birthweight


create a regression model, using length at birth and gestational age as main predictors

```{r}
main_eff_model = 
  child_bw_data %>% 
  lm(bwt ~ blength + gaweeks, data = .)
main_eff_model %>% 
  broom::tidy()
```

```{r}
# this chunk of code should appear above
child_bw_data %>% 
  modelr::add_residuals(main_eff_model) %>% 
  modelr::add_predictions(main_eff_model) %>%
  ggplot(aes(x = resid, y = pred)) + geom_point()
```

create a regression model, using head circumference, length, sex, and all interactions as main 
predictors

```{r}
interact_model = 
  child_bw_data %>% 
  lm(bwt ~ bhead + blength + babysex + bhead * blength + 
     bhead * babysex + blength * babysex, data = .) %>% 
  broom::tidy()
```


### Comparison

```{r}
cv_df = 
  crossv_mc(child_bw_data, 100) %>% 
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble)
  )

cv_df = 
  cv_df %>% 
  mutate(
    main_mod = map(train, ~lm(bwt ~ blength + gaweeks, data = .x)),
    interact_mod = map(train, ~lm(bwt ~ bhead + blength + babysex + bhead * blength + 
     bhead * babysex + blength * babysex, data = .x))
  ) %>% 
  mutate(
    rmse_main = map2_dbl(main_mod, test, ~rmse(model = .x, data = .y)),
    rmse_interact = map2_dbl(interact_mod, test, ~rmse(model = .x, data = .y))
  )

cv_df %>% 
  select(rmse_main, rmse_interact) %>% 
  pivot_longer(
    everything(),
    names_to = "model",
    values_to = "rmse"
  ) %>% 
  ggplot(aes(x = model, y = rmse)) + geom_violin()
```





